- name: Ensuring we have local user
  user:
    name: "{{ compose_user }}"
    state: present

- name: Authorized_key for local user
  authorized_key:
    user: "{{ compose_user }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ compose_ssh_keys }}"

- name: Ensuring we have local directory for composes content
  file:
    path: "{{ composes_local_dir }}"
    state: directory
    mode: 0755
    owner: "{{ compose_user }}"
    group: "{{ compose_user }}"

- import_role:
    name: httpd
  vars:
    httpd_html_autoindex_title: "CentOS Composes Mirror"
    httpd_html_autoindex_content: "{{ compose_httpd_header }}"

- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ inventory_hostname }}"
  tags:
    - tls

- import_role:
    name: httpd
    tasks_from: tls
  tags:
    - tls


- name: Adding vhost file
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
  notify:
    - reload_httpd
  with_items:
    - 30_composes.conf
    - ssl-composes.conf
  tags:
    - httpd

- name: Ensuring some selinux booleans are enabled
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: yes
  with_items:
    - httpd_enable_homedirs
    - httpd_read_user_content

